name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_DEPLOYMENT: ${{ contains(join(github.events.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint

      - name: Build production code
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: install playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !env.SKIP_DEPLOYMENT  }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Discord Notify Success
        if: ${{ success() }}
        uses: Ilshidur/action-discord@master
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          details: Successful deployment

      - name: Discord Notify Failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: |
            Error in deployment!:
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.event.head_commit.message }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.env.SKIP_DEPLOYMENT == 'false'}}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
